# Auto-generated by Terraform. Do not edit by hand -- re-run `terraform apply`
# and this file will be regenerated. Copy or symlink it into
# ansible/inventory/hosts.ini.

%{ for key, inst in instances ~}
[${replace(inst.role, "-", "_")}]
${inst.name} ansible_host=${inst.public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${private_key_path}

%{ endfor ~}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
